name: "Blog of lib"
description: "Web Front-End Blog by lib"

url: "http://scnu.top:4000"
loadingImg: "http://7xl1oi.com1.z0.glb.clouddn.com/loading.gif"
filePath: "http://7xl1oi.com1.z0.glb.clouddn.com/"

timezone: Asia/Shanghai

paginate: 20

highlighter: pygments

markdown: rdiscount
permalink: pretty


gems: [jekyll-paginate]
